### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by luckcoolla** [Yalantis/StarWars.Android#2]
12-22 18:49:23.012 16155-16345/... E/AndroidRuntime: FATAL EXCEPTION: GLThread 3428
                                                                  Process: ..., PID: 16155
                                                                  java.lang.IndexOutOfBoundsException: offset=15120, count=3, length=15120
                                                                      at java.nio.Buffer.checkPutBounds(Buffer.java:179)
                                                                      at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:378)
                                                                      at java.nio.ByteBufferAsFloatBuffer.put(ByteBufferAsFloatBuffer.java:159)
                                                                      at com.yalantis.starwars.render.Buffers.makeInterleavedBuffer(Buffers.java:30)
                                                                      at com.yalantis.starwars.render.GenerateVerticesData$1.run(GenerateVerticesData.java:45)
                                                                      at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1463)
                                                                      at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

Это случилось, когда я подложил TilesFrameLayout под основной экран программы, view там достаточно тяжелая - ViewPager внутри фрагмента, listView и SurfaceView. Есть ли варианты избежать падения?
It happened when I planted Tiles FrameLayout under the main program screen, view there is heavy - ViewPager inside track, listView and SurfaceView. Are there options to avoid the drop?

**Comment by defHLT** [comment]
Thanks for reporting this.
Could you please provide more details? Does it crash consistently on every device you own? What specific attributes (like sw_numberOfTilesX) do you use? I can't reproduce this crash so far.
